features/ipynbconversion
Bycelium/PyFlow pull request #117
Opened 2021-12-14 22:15 UTC by FabienRoger

Add more features and tests for ipynb conversion

2021-12-14 22:19 UTC, FabienRoger commented
I think the test I added cause an out-of-memory error. I don't know how to fix it.

2021-12-16 12:11 UTC, MathisFederico requested changes
Can't wait to merge that ! Tests are always welcome !

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +    """Testing function_parsing functions"""
Wrong name, also look at clipboard test for naming conventions, they are different for tests.

```suggestion
    """Conversion from .ipynb"""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +        """Empty data should return empty document"""
```suggestion
        """should return empty graph for empty data."""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +    ipyg_data = ipynb_to_ipyg(ipynb_data)
Those should be inputs for more modular behavior

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +        """The conversion for an empty notebook should be coherent"""
```suggestion
        """should return empty graph for empty notebook data."""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +        """The conversion for a usual notebook should be coherent"""
```suggestion
        """should return expected graph for usual notebook data."""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +        """The conversion for a complex notebook should be coherent"""
```suggestion
        """should return expected graph for complex notebook data."""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +        """Should return True iff the given text can be used as a title for a block"""
```suggestion
        """should return True iff the given text can be used as a title for a block."""
```

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +    6. markdown blocks that always have text
Do not comply with google docstring guidelines that we follow : https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings

Btw we should add that to CONTRIBUTING.md, you can do it if you want to.

2021-12-16 12:11 UTC, MathisFederico commented on tests/unit/scene/test_ipynb_conversion.py
> +    # 1.
Use text instead of numbers.
```suggestion
    # Blocks and edges
```

2021-12-19 12:27 UTC, MathisFederico approved these changes
Perfect !
Thank you a lot !
Tests are always very welcome !

2021-12-19 12:27 UTC, merged