:beetle: Change file dialog settings
Bycelium/PyFlow pull request #223
Opened 2022-01-15 09:15 UTC by FabienRoger

Fixes #156

2022-01-15 15:46 UTC, MathisFederico requested changes
We still need to restrict what files can be opened in the first place, although a better tooltip is welcome !

2022-01-15 15:46 UTC, MathisFederico commented on pyflow/graphics/window.py
> +            "Ipygraph or Juyter notebook (*.ipyg *.ipynb)",
```suggestion
            "Interactive python graph or notebook (*.ipyg *.ipynb)",
```

2022-01-16 09:09 UTC, FabienRoger commented
This does restrict the files that can be opened!

2022-01-16 13:58 UTC, MathisFederico approved these changes
Nice !

2022-01-16 13:58 UTC, merged