🪲 Fix the arrow bug
Bycelium/PyFlow pull request #225
Opened 2022-01-15 11:12 UTC by FabienRoger

Fixes #162

2022-01-15 16:04 UTC, MathisFederico requested changes
A few changes I see

2022-01-15 16:04 UTC, MathisFederico commented on pyflow/core/mdeditor.py
> +        return super().focusOutEvent(event)
This should be in pyflow.blocks not pyflow.core (and I guess pyeditor should also be at pyflow.blocks.codeblock.pyeditor as it is only used in codeblock)

2022-01-15 16:04 UTC, MathisFederico commented on pyflow/blocks/widgets/blocktitle.py
> +        block_item: QGraphicsItem,
```suggestion
        parent: QGraphicsItem,
```

2022-01-16 13:08 UTC, MathisFederico commented
My previous comment on renaming block_item is not resolved

2022-01-16 13:30 UTC, FabienRoger commented
I changed the name to parent_block because parent is already a field of the QLineEdit class.

2022-01-16 14:04 UTC, MathisFederico approved these changes
A nice fix and refactor !

2022-01-16 14:06 UTC, merged