:tada: Adds kernel menu to control kernel
Bycelium/PyFlow pull request #282
Opened 2022-02-19 16:19 UTC by AlexandreSajus

![image](https://user-images.githubusercontent.com/62465003/154809276-51c4ee19-e973-4891-9f49-4d81d7637166.png)

2022-02-19 22:13 UTC, MathisFederico requested changes

2022-02-19 22:13 UTC, MathisFederico commented on pyflow/graphics/window.py
> +            self.statusbar.showMessage("No active window")
Those functions are nearly the same, try to reduce duplication by using an other (private) method

2022-02-20 15:01 UTC, AlexandreSajus commented
Restarting the kernel introduces weird bugs.

For example:
![image](https://user-images.githubusercontent.com/62465003/154848907-b02f9168-d387-4709-bff1-f05fdc3be8b5.png)

I ran A then restarted the kernel and ran B. B should output an error but does not.

Plus I would need to reset the kernel CWD every time I restart the kernel which means accessing saving_path from where I restart the kernel.

I am closing this PR for the time being

2022-02-20 15:01 UTC, closed without merging

2022-02-20 16:10 UTC, MathisFederico commented
That's sad, this would be a very nice feature :/